[greeter]
icon-theme-name = hicolor
font-name = Noto Sans Medium 12
background = #FDF6E3
hide-user-image = true
clock-format = %H:%M:%S
indicators = ~power
theme-name = NumixSolarizedLightYellow
user-background = false
screensaver-timeout = 0

