[greeter]
theme-name = NumixSolarizedLightYellow
icon-theme-name = hicolor
user-background = false
background = #FDF6E3
font-name = Noto Sans Medium 12
hide-user-image = true
clock-format = %H:%M:%S
indicators = ~power
screensaver-timeout = 0

