font_family Hack Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12

background #FDF6E3
foreground #657B83
cursor #586E75
selection_background #475B62
selection_foreground #EAE3CB
color0 #EEE8D5
color1 #DC322F
color2 #859900
color3 #B58900
color4 #268BD2
color5 #D33682
color6 #2AA198
color7 #073642
color8 #002B36
color9 #CB4B16
color10 #93A1A1
color11 #839496
color12 #657B83
color13 #6c71c4
color14 #586E75
color15 #002B36

shell /usr/bin/bash
